// AUTO-GENERATED by bake/make_fixtures.py -- do not edit by hand.
// Exact astropy Galactic->ICRS rotation matrix (3x3). M @ v_gal = v_icrs.
// This is the frame DEFINITION, sourced from astropy so the engine's convention
// matches the bake. See spec section 3.
export const GALACTIC_TO_ICRS: readonly (readonly number[])[] = [
  [-0.05487565771259163, 0.4941094371927268, -0.8676661375596576],
  [-0.8734370519556159, -0.4448297212232952, -0.19807633727300053],
  [-0.48383507361671546, 0.7469821839866676, 0.4559838136873016],
];
