// AUTO-GENERATED by bake/make_galactic_fixtures.py -- do not edit by hand.
// Galactocentric frame (from astropy) + the Milky Way potential, for galactic-orbit
// propagation. Lengths kpc, velocities km/s, masses Msun, time Myr.

export const KM_S_TO_KPC_MYR = 0.0010227121650537077;
export const G_KPC_MSUN_MYR = 4.498502151469552e-12;

// rotation: heliocentric-galactic axes -> galactocentric axes
export const GALACTIC_TO_GALACTOCENTRIC: readonly (readonly number[])[] = [
  [0.9999967244375796, 9.339629611915257e-07, 0.0025595142573155982],
  [-9.302064829519452e-07, 0.9999999999984879, -1.4688441507537675e-06],
  [-0.0025595142586860575, 1.466458464216558e-06, 0.9999967244369389],
];

// rotation: galactocentric axes -> ICRS axes (apparent direction)
export const GALACTOCENTRIC_TO_ICRS: readonly (readonly number[])[] = [
  [-0.0570958203337113, 0.4941107627040048, -0.8675221158451737],
  [-0.8739415856218073, -0.44482861780254446, -0.19584076619723056],
  [-0.4826656940587988, 0.7469819642829032, 0.45722179827168574],
];

export const SUN_GALACTOCENTRIC = { pos_kpc: [-8.1219733661223, 0.0, 0.020800000000000003], vel_kms: [12.9, 245.6, 7.78] } as const;

export const MW_POTENTIAL = {"bulge": {"M": 5000000000.0, "a": 0.5}, "disk": {"M": 70000000000.0, "a": 3.0, "b": 0.28}, "halo": {"M": 700000000000.0, "rs": 16.0}} as const;
