// Markdown rendering (Phase 8 Gate B). Turns the structured Dossier object into the printed
// document: findings-prose first per section, full appendix tables last (section 8), so
// every number in the prose is checkable against a table. Pure string formatting -- no
// computation happens here; see sections.ts for that. Deterministic: same Dossier object ->
// byte-identical markdown, always (no Date.now(), no Math.random(), no locale-dependent
// number formatting).
import type { Dossier, StarRow, RiseSetRow, SeasonSummary } from "./sections.js";
import { toLocalDays, type World } from "./geometry.js";

const fx = (n: number, d = 2): string => (Number.isFinite(n) ? n.toFixed(d) : "—");

/** "X.XX local days" using this world's SOLAR day, or a real-day fallback (explicitly
 *  labeled) when the world is locked and has no local day. */
function fmtLocalDays(w: World, years: number, d = 2): string {
  const ld = toLocalDays(w, years);
  return ld != null ? `${fx(ld, d)} local days` : `${fx(years * 365.25, d)} real days (no local day on this world)`;
}
function fmtTime(solarDayHours: number | null, years: number): string {
  const sign = years >= 0 ? "+" : "";
  const localDay = solarDayHours == null ? null : (years * 31_557_600) / (solarDayHours * 3600);
  return `${sign}${fx(years, 4)} yr${localDay != null ? ` (local day ${fx(localDay, 1)})` : ""}`;
}
function azCompass(deg: number): string {
  const dirs = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"];
  return dirs[Math.round(((deg % 360) / 22.5)) % 16]!;
}

function table(headers: string[], rows: (string | number)[][]): string {
  const h = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.map((c) => (typeof c === "number" ? fx(c, 3) : c)).join(" | ")} |`).join("\n");
  return `${h}\n${sep}\n${body}`;
}

export function renderMarkdown(d: Dossier): string {
  const w = d.world;
  const out: string[] = [];
  out.push(`# Dossier — ${d.s1.worldName}`);
  out.push(`### Site: ${d.site.label} (${fx(d.site.latDeg, 4)}°, ${fx(d.site.lonDeg, 4)}°)`);
  out.push("");
  out.push("*Computed observational truth for this world, from this site. Every figure below is derived directly from the engine's orbital mechanics — nothing here is named, dated to a real calendar, or interpreted. That is the artist's work; this document is the machine's report of what the sky does.*");
  out.push("");
  out.push(sec1(d));
  out.push(sec2(d));
  out.push(sec3(d));
  out.push(sec4(d));
  out.push(sec5(d));
  out.push(sec6(d));
  out.push(sec7(d));
  out.push(sec8(d));
  out.push(`\n---\n*Generated by tools/emit_dossier.ts · catalog: ${d.generatedFromCatalog} · world schema ${w.schema_version}*\n`);
  return out.join("\n");
}

function sec1(d: Dossier): string {
  const s = d.s1;
  const lines: string[] = ["## 1 · The World", ""];
  lines.push(`**${s.worldName}**${s.worldType ? ` — a *${s.worldType.replace(/_/g, " ")}* world` : ""}${s.ageGyr != null ? `, ${fx(s.ageGyr, 2)} Gyr old` : ""}.`);
  lines.push("");
  lines.push(`Host star: ${s.host.catalogId ?? "(no real catalog anchor)"} — a real catalog identity at galactic position (${fx(s.host.posPc[0])}, ${fx(s.host.posPc[1])}, ${fx(s.host.posPc[2])}) pc. ${fx(s.host.massMsun)} M☉, ${fx(s.host.luminosityLsun)} L☉, ${Math.round(s.host.teffK)} K, ${fx(s.host.radiusRsun)} R☉.`);
  lines.push("");
  lines.push(`Planet: ${Math.round(s.planet.radiusKm)} km radius, ${fx(s.planet.massMearth)} M⊕, orbiting at ${fx(s.planet.aAu, 3)} AU (e = ${fx(s.planet.e, 3)}), axial tilt ${fx(s.planet.axialTiltDeg, 2)}°. ${s.moonCount} moon${s.moonCount === 1 ? "" : "s"}.`);
  lines.push("");
  const latNote = s.latitudeClass === "tropical-equivalent" ? "within the sub-stellar excursion — the host star can stand directly overhead here at some point in the year"
    : s.latitudeClass === "polar-equivalent" ? "beyond the polar-night/midnight-sun threshold for this world's tilt — the host star can become circumpolar or vanish entirely for stretches"
      : "outside the sub-stellar excursion but short of the polar threshold — an ordinary mid-latitude site with a real but bounded seasonal swing";
  lines.push(`Observer site: ${fx(s.site.latDeg, 4)}°, ${fx(s.site.lonDeg, 4)}° — **${s.latitudeClass}** (${latNote}).`);
  if (s.provenance) {
    lines.push("");
    lines.push("<details><summary>Provenance (real vs. derived/sampled)</summary>\n");
    for (const [k, p] of Object.entries(s.provenance)) lines.push(`- **${k}**: ${p.real ? "real" : "derived"} — ${p.note}`);
    lines.push("\n</details>");
  }
  lines.push("");
  lines.push("*Engine queries: `World`/`HostStar`/`Planet` schema fields; generator provenance record.*");
  return lines.join("\n");
}

function sec2(d: Dossier): string {
  const s = d.s2;
  const lines: string[] = ["\n## 2 · The Day & The Year", ""];
  if (s.locked) {
    lines.push(`**This world has no day.** Rotation period (${fx(s.rotationDays, 3)} d) equals orbital period (${fx(s.orbitYears, 4)} yr) — the planet is spin-orbit locked. There is no sunrise or sunset at this site; the host star sits at a fixed point in the sky.`);
    lines.push("");
    lines.push(`Fixed host-star position at this site: **altitude ${fx(s.fixedSun!.altDeg, 2)}°, azimuth ${fx(s.fixedSun!.azDeg, 2)}° (${azCompass(s.fixedSun!.azDeg)})**${s.fixedSun!.altDeg < 0 ? " — below the horizon; this site never sees the host star" : ""}.`);
    lines.push("");
    lines.push("*(Orbital eccentricity can cause a small longitudinal libration of the sub-stellar point over one orbit; not tabulated here — see the appendix for the raw orbit elements.)*");
  } else {
    lines.push(`Sidereal rotation (spin relative to the stars): **${fx(s.rotationDays, 4)} d** (${fx(s.rotationDays * 24, 2)} h). Solar day — 1 **local day**, sunrise to sunrise: **${fx((s.solarDayHours ?? 0) / 24, 4)} d** (${fx(s.solarDayHours ?? 0, 2)} h)${Math.abs((s.solarDayHours ?? 0) - s.rotationDays * 24) > 0.01 ? " — measurably longer than the sidereal spin, because the planet's own orbital motion adds one apparent rotation per year" : ""}. Orbit (local year): **${fx(s.orbitYears, 4)} yr**.`);
    lines.push("");
    lines.push(`Day : year ratio — **${s.daysPerYearWhole} local days, plus ${fx(s.daysPerYearRemainder, 4)} of a day** (${fx(s.daysPerYearRemainder * (s.solarDayHours ?? 0), 2)} h). That remainder is what any calendar built on whole days must reconcile.`);
    lines.push("");
    const sq = s.solstices!;
    lines.push(`Solstices/equinoxes (years-since-epoch, local day in parens): summer ${fmtTime(s.solarDayHours, sq.summer)}; winter ${fmtTime(s.solarDayHours, sq.winter)}; equinox ${fmtTime(s.solarDayHours, sq.equinox1)}; equinox ${fmtTime(s.solarDayHours, sq.equinox2)}.`);
    lines.push("");
    const ys = s.yearScan!;
    if (ys.anyCircumpolarDay || ys.anyPolarNight) {
      lines.push(`At this site the host star is **circumpolar or absent for part of the year** (polar-equivalent latitude) — day length is undefined on those dates.`);
    } else {
      lines.push(`Day length over the year: **${fx(ys.minDayHours, 2)} h to ${fx(ys.maxDayHours, 2)} h**.`);
    }
    lines.push("");
    lines.push(`Sunrise-azimuth range over the year (the Chankillo span): **${fx(ys.minRiseAz, 1)}° to ${fx(ys.maxRiseAz, 1)}°** (${azCompass(ys.minRiseAz)} to ${azCompass(ys.maxRiseAz)}), a swing of ${fx(ys.maxRiseAz - ys.minRiseAz, 1)}°.`);
  }
  lines.push("");
  lines.push("*Engine queries: `orbitalPeriodYears`-equivalent (Kepler III), `findRiseSetTransit`, `inertialToHorizontal`, plus this tool's `findSolsticesEquinoxes`/`siteYearScan` (geometry.ts) built on them.*");
  return lines.join("\n");
}

function sec3(d: Dossier): string {
  const s = d.s3, w = d.world;
  const lines: string[] = ["\n## 3 · The Moons", ""];
  if (w.moons.length === 0) { lines.push("*No moons.*"); return lines.join("\n"); }
  for (const m of s.moons) {
    const periodStr = m.periodLocalDays != null ? `${fx(m.periodLocalDays, 3)} local days` : `${fx(m.periodYears * 365.25, 3)} real days (no local day on this world)`;
    lines.push(`**${m.name}** — orbital period ${periodStr}; synodic (phase) period ${m.synodicNote}. Inclination ${fx(m.incDeg, 2)}° (to the system's reference plane), eccentricity ${fx(m.e, 3)}: apparent size ranges from ${fx(m.angDiamMinDeg * 3600, 0)}″ to ${fx(m.angDiamMaxDeg * 3600, 0)}″ over one orbit.`);
    lines.push("");
  }
  if (s.chord.length) {
    lines.push("**The chord** (period ratios between adjacent moons):");
    for (const c of s.chord) lines.push(`- ${c.a} : ${c.b} = ${fx(c.ratio, 4)}${c.nearest ? ` — near **${c.nearest}** resonance` : ""}`);
    lines.push("");
  }
  if (s.alignmentRecurrenceYears != null) {
    lines.push(`The full multi-moon configuration recurs (all moons return near their starting phase together) every **${fmtLocalDays(w, s.alignmentRecurrenceYears, 2)}**.`);
    lines.push("");
  }
  lines.push("Year vs. month, in whole numbers:");
  for (const y of s.yearMonthTable) lines.push(`- ${y.moon}: **${y.monthsPerYear} months** per local year, remainder **${y.remainderDays != null ? `${fx(y.remainderDays, 2)} days` : "— (no local day on this world)"}**.`);
  lines.push("");
  lines.push("*Engine queries: `keplerPosition`/Kepler III on each moon's `a_au` about the planet's mass; this tool's `synodicYears`/`resonanceChord`/`alignmentRecurrenceYears` (geometry.ts).*");
  return lines.join("\n");
}

function sec4(d: Dossier): string {
  const s = d.s4, w = d.world;
  const lines: string[] = ["\n## 4 · Eclipses & Alignments", ""];
  if (w.moons.length === 0) { lines.push("*No moons — no eclipses.*"); return lines.join("\n"); }
  lines.push(`Scanned **${fx(s.scanSpanYears / (d.s2.orbitYears || 1), 1)} local years** (${fx(s.scanSpanYears, 2)} Julian years) for host-star × moon occultations and close conjunctions.`);
  lines.push("");
  for (const pm of s.perMoon) {
    if (pm.seasons.length === 0) { lines.push(`**${pm.moon}**: no occultation/conjunction events found in the scan window (its inclination keeps it clear of the host star's apparent path at this scan's resolution).`); lines.push(""); continue; }
    const avgEvents = pm.seasons.reduce((a, s2) => a + s2.eventCount, 0) / pm.seasons.length;
    const avgDur = pm.seasons.reduce((a, s2) => a + (s2.endYears - s2.startYears), 0) / pm.seasons.length;
    lines.push(`**${pm.moon}**: **${pm.seasons.length} eclipse seasons** in the scan window`
      + (pm.avgSpacingYears != null ? `, spaced ~**${pm.avgSpacingLocalDays != null ? `${fx(pm.avgSpacingLocalDays, 1)} local days` : `${fx(pm.avgSpacingYears * 365.25, 1)} real days (no local day on this world)`}** apart` : "")
      + `, averaging **${fx(avgEvents, 1)} events** over **${fmtLocalDays(w, avgDur, 1)}** each.`);
    if (pm.masterCycleYears != null) {
      const residual = pm.masterCycleResidualLocalDays != null ? `${fx(pm.masterCycleResidualLocalDays, 2)} days` : `${fx((pm.masterCycleResidualYears ?? 0) * 365.25, 2)} real days (no local day on this world)`;
      lines.push(`  Master cycle: seasons repeat with period **${fmtLocalDays(w, pm.masterCycleYears, 1)}** (one full local year — this engine models no nodal precession, so the cycle does not drift; empirical residual **${residual}**, i.e. no detectable Saros-like beat).`);
    }
    lines.push("");
  }
  if (s.pairSynodic.length) {
    lines.push("Moon-pair conjunction cycles (synodic periods):");
    for (const p of s.pairSynodic) lines.push(`- ${p.a} × ${p.b}: every **${p.synodicLocalDays != null ? `${fx(p.synodicLocalDays, 2)} local days` : p.synodicYears != null ? `${fx(p.synodicYears * 365.25, 2)} real days (no local day on this world)` : "— (no recurring conjunction)"}**`);
    lines.push("");
  }
  lines.push("*Engine queries: `findMinSeparation` (per-orbit local minima, windowed around analytic node-crossings of the host star's ecliptic longitude); this tool's `scanEclipseSeasons` (geometry.ts).*");
  return lines.join("\n");
}

function sec5(d: Dossier): string {
  const s = d.s5;
  const lines: string[] = ["\n## 5 · The Stars", ""];
  lines.push(`The 30 brightest stars from this vantage (full table in the appendix). Brightest: **${s.brightest[0]?.designation}** at magnitude ${fx(s.brightest[0]?.magnitude ?? 0, 2)}.`);
  lines.push("");
  if (s.excludedNearHost > 0) {
    lines.push(`*(${s.excludedNearHost} catalog entr${s.excludedNearHost === 1 ? "y" : "ies"} within ${0.1} pc of the host star's own position ${s.excludedNearHost === 1 ? "was" : "were"} excluded as a cross-matched duplicate detection of the host itself, not a distinct background star — see \`HOST_DUPLICATE_EXCLUSION_PC\` in geometry.ts.)*`);
    lines.push("");
  }
  lines.push(`North pole: ${s.northPole ? `**${s.northPole.star}**, ${fx(s.northPole.sepDeg, 2)}° off (mag ${fx(s.northPole.mag, 2)})` : "**empty** — no naked-eye star within 20° of the pole"}.`);
  lines.push(`South pole: ${s.southPole ? `**${s.southPole.star}**, ${fx(s.southPole.sepDeg, 2)}° off (mag ${fx(s.southPole.mag, 2)})` : "**empty** — no naked-eye star within 20° of the pole"}.`);
  lines.push("");
  if (s.groupings.length) {
    lines.push(`**${s.groupings.length} tight naked-eye groupings** (≤3° apart, among stars mag ≤ 4) — candidate asterism seeds, listed by designation only:`);
    for (const g of s.groupings.slice(0, 20)) lines.push(`- ${g.a} — ${g.b} (${fx(g.sepDeg, 2)}°)`);
    if (s.groupings.length > 20) lines.push(`- *(${s.groupings.length - 20} more in the appendix)*`);
  } else {
    lines.push("No tight naked-eye groupings found among the brightest stars at this vantage.");
  }
  lines.push("");
  lines.push(`Milky Way band: reaches **${fx(s.milkyWay.maxAltDeg, 1)}°** altitude at this site — ${s.milkyWay.classification}${s.milkyWay.horizonCrossingsAzDeg.length === 2 ? `, crossing the horizon near ${azCompass(s.milkyWay.horizonCrossingsAzDeg[0]!)} and ${azCompass(s.milkyWay.horizonCrossingsAzDeg[1]!)}` : ""}.`);
  lines.push("");
  lines.push(s.zenith.length ? `Zenith stars (pass within 2° of overhead once per rotation): ${s.zenith.join(", ")}.` : "No catalog stars from the brightest 30 pass within 2° of the zenith at this latitude.");
  lines.push("");
  lines.push("*Engine queries: `relocateStar` (Stage 1) over the full catalog; this tool's `nearestToPole`/`tightGroupings`/`milkyWayAtSite`/`zenithStars` (geometry.ts); Milky Way orientation via `helioToGalcen`/`galactocentricToIcrs`.*");
  return lines.join("\n");
}

function sec6(d: Dossier): string {
  const s = d.s6;
  const lines: string[] = ["\n## 6 · Rising & Setting", ""];
  lines.push("Rise/set azimuths for the 30 brightest stars (full table in the appendix) — the raw data for a star compass.");
  lines.push("");
  if (s.circumpolar.length) lines.push(`Circumpolar at this site: ${s.circumpolar.join(", ")}.`);
  else lines.push("No circumpolar stars among the brightest 30 at this site.");
  lines.push("");
  if (s.sharedHouses.length) {
    lines.push(`**${s.sharedHouses.length} shared rising houses** (stars rising within the same 5°-wide azimuth bin):`);
    for (const h of s.sharedHouses.slice(0, 15)) lines.push(`- ~${h.binCenterDeg}° (${azCompass(h.binCenterDeg)}): ${h.stars.join(", ")}`);
  } else {
    lines.push("No two of the brightest 30 share a rising house (5° bins).");
  }
  lines.push("");
  const withHeliacal = s.rows.filter((r) => r.heliacalRisingYears != null || r.heliacalSettingYears != null);
  if (withHeliacal.length) {
    lines.push(`Heliacal rising/setting dates found for ${withHeliacal.length} of the 30 (calendar-anchor stars; full dates in the appendix).`);
  }
  lines.push("");
  lines.push("*Engine queries: `findRiseSetTransit` + `inertialToHorizontal` at the rise/set moments; this tool's `heliacalDates` (geometry.ts, arcus-visionis proxy: sun between -6° and -18° altitude at the star's rise/set).*");
  return lines.join("\n");
}

function sec7(d: Dossier): string {
  const s = d.s7;
  const lines: string[] = ["\n## 7 · Deep Time", ""];
  for (const span of s.driftSpans) {
    const within = span.withinCap ? "within the validated range" : "**beyond the honest cap — extrapolation, not data**";
    const maxDrift = Math.max(...span.drift.map((x) => x.driftDeg));
    lines.push(`**${span.localYears.toLocaleString()} local years** (${span.realYears.toExponential(2)} yr) — ${within}. The fastest of the top-10 brightest stars drifts up to **${fx(maxDrift, 3)}°**${maxDrift > 1 ? " — enough to visibly deform a tight grouping over that span" : ""}.`);
  }
  lines.push("");
  lines.push("**Axial precession is not modeled** in this engine — the spin pole's RA/Dec is fixed for all simulated time. A real planet's precession (Earth's is ~26,000 yr) would slowly rotate every rising/setting/zenith/pole table in this document; none of that motion is represented here.");
  lines.push("");
  lines.push(`Honest caps: rectilinear propagation is validated to **${s.honestCapRectilinearYears.toExponential(0)} yr**; galactic-orbit propagation to **${s.honestCapGalacticYears.toExponential(0)} yr**. Figures beyond these are extrapolation.`);
  lines.push("");
  lines.push("*Engine queries: `relocateStar` at two epochs (this tool's `properMotionDriftDeg`, geometry.ts); `PROPAGATION_MODELS` honest-cap metadata.*");
  return lines.join("\n");
}

function sec8(d: Dossier): string {
  const lines: string[] = ["\n## 8 · Appendix — full tables", ""];

  lines.push("### 8.1 World parameters");
  lines.push(table(["field", "value"], [
    ["world_type", d.s1.worldType ?? "—"], ["age_gyr", d.s1.ageGyr ?? "—"],
    ["host.catalog_id", d.s1.host.catalogId ?? "—"], ["host.mass_msun", d.s1.host.massMsun],
    ["host.luminosity_lsun", d.s1.host.luminosityLsun], ["host.teff_k", d.s1.host.teffK],
    ["host.radius_rsun", d.s1.host.radiusRsun], ["planet.radius_km", d.s1.planet.radiusKm],
    ["planet.mass_mearth", d.s1.planet.massMearth], ["planet.a_au", d.s1.planet.aAu],
    ["planet.e", d.s1.planet.e], ["planet.axial_tilt_deg", d.s1.planet.axialTiltDeg],
    ["site.lat_deg", d.site.latDeg], ["site.lon_deg", d.site.lonDeg],
  ]));

  lines.push("\n### 8.2 Calendar");
  const s2 = d.s2;
  if (s2.locked) {
    lines.push(table(["field", "value"], [["rotation_days_sidereal", s2.rotationDays], ["orbit_years", s2.orbitYears],
      ["fixed_sun_alt_deg", s2.fixedSun!.altDeg], ["fixed_sun_az_deg", s2.fixedSun!.azDeg]]));
  } else {
    lines.push(table(["field", "value"], [
      ["rotation_days_sidereal", s2.rotationDays], ["solar_day_hours", s2.solarDayHours ?? "—"], ["orbit_years", s2.orbitYears],
      ["days_per_year_local", s2.orbitDaysInLocalDays], ["summer_solstice_yr", s2.solstices!.summer],
      ["winter_solstice_yr", s2.solstices!.winter], ["equinox_1_yr", s2.solstices!.equinox1],
      ["equinox_2_yr", s2.solstices!.equinox2], ["min_day_hours", s2.yearScan!.minDayHours],
      ["max_day_hours", s2.yearScan!.maxDayHours], ["min_rise_az_deg", s2.yearScan!.minRiseAz],
      ["max_rise_az_deg", s2.yearScan!.maxRiseAz],
    ]));
  }

  lines.push("\n### 8.3 Moons");
  if (d.s3.moons.length) {
    lines.push(table(["moon", "period_local_days", "synodic", "inc_deg", "e", "ang_diam_min_arcsec", "ang_diam_max_arcsec"],
      d.s3.moons.map((m) => [m.name, m.periodLocalDays ?? "—", m.synodicNote, m.incDeg, m.e, m.angDiamMinDeg * 3600, m.angDiamMaxDeg * 3600])));
  } else lines.push("*(none)*");

  lines.push("\n### 8.4 Eclipse seasons (per moon, summarized)");
  const allSeasons: SeasonSummary[] = d.s4.perMoon.flatMap((p) => p.seasons);
  if (allSeasons.length) {
    lines.push(table(["moon", "start_yr", "end_yr", "duration_local_days", "event_count", "min_sep_deg"],
      allSeasons.map((s) => [s.moon, s.startYears, s.endYears, toLocalDays(d.world, s.endYears - s.startYears) ?? "—", s.eventCount, s.minSepDeg])));
  } else lines.push("*(no eclipse events found)*");

  lines.push("\n### 8.5 Brightest 30 stars");
  lines.push(table(["designation", "mag", "bp_rp", "dist_pc", "visibility"],
    d.s5.brightest.map((r: StarRow) => [r.designation, r.magnitude, r.colorIndex, r.distancePc, r.visibility])));
  lines.push("\n### 8.6 Tight groupings (full)");
  if (d.s5.groupings.length) lines.push(table(["a", "b", "sep_deg"], d.s5.groupings.map((g) => [g.a, g.b, g.sepDeg])));
  else lines.push("*(none)*");

  lines.push("\n### 8.7 Rising & setting (brightest 30)");
  lines.push(table(["designation", "rise_az_deg", "set_az_deg", "visibility", "heliacal_rising_yr", "heliacal_setting_yr"],
    d.s6.rows.map((r: RiseSetRow) => [r.designation, r.riseAzDeg ?? "—", r.setAzDeg ?? "—", r.visibility, r.heliacalRisingYears ?? "—", r.heliacalSettingYears ?? "—"])));

  lines.push("\n### 8.8 Deep-time drift (top 10 brightest)");
  for (const span of d.s7.driftSpans) {
    lines.push(`\n**${span.localYears} local years:**`);
    lines.push(table(["star", "drift_deg"], span.drift.map((x) => [x.star, x.driftDeg])));
  }

  return lines.join("\n");
}
